CREATE TABLE IF NOT EXISTS incoming_c2b_mpesa_confirmation_requests(
	id serial PRIMARY KEY,
	transaction_type varchar(30) NULL DEFAULT '',
	trans_id varchar(30) NULL DEFAULT '',
	trans_time varchar(30) NULL DEFAULT '',
	trans_amount varchar(30) NULL DEFAULT '',
	business_short_code varchar(30) NULL DEFAULT '',
	bill_ref_number varchar(30) NULL DEFAULT '',
	invoice_number varchar(30) NULL DEFAULT '',
	org_account_balance varchar(30) NULL DEFAULT '',
	third_party_trans_id varchar(30) NULL DEFAULT '',
	msisdn varchar(30) NULL DEFAULT '',
	first_name varchar(30) NULL DEFAULT '',
	middle_name varchar(30) NULL DEFAULT '',
	last_name varchar(30) NULL DEFAULT '',
	payment_type varchar(20) NULL DEFAULT 'MPESA',
	bill_type varchar(20) NULL DEFAULT 'C2B',
	transaction_date timestamp NULL DEFAULT current_timestamp,
	stk_push_txn boolean NULL DEFAULT 'false',
	duplicate_entry boolean NULL DEFAULT 'false',
	booked_entry boolean NULL DEFAULT 'false',
	posted_to_cbs boolean NULL DEFAULT 'false',
	trials_cbs smallint NULL DEFAULT 0,
	post_picked_cbs boolean NULL DEFAULT 'false',
	date_to_cbs timestamp NULL,
	date_from_cbs timestamp NULL,
	status_code_cbs smallint NULL DEFAULT 1,
	status_message_cbs varchar(300) NULL DEFAULT '',
	txn_ref_cbs int NULL DEFAULT 0,
	date_added timestamp NULL DEFAULT current_timestamp,
	date_updated timestamp NULL
)